# This is a basic workflow to help you get started with Actions

name: linux

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main, dev ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    name: "Linux OpenOasis Actions"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: mpi4py/setup-mpi@v1
      - name: Install GCC-10
        run: |
          sudo apt-get update
          sudo apt install gcc-10 g++-10 -y
          gcc --version
          g++ --version
          ls /usr/bin/gcc*
        shell: bash        
      - name: Install Third party library
        run: |
          git clone https://github.com/pybind/pybind11.git
          cd  pybind11
          mkdir build
          cd build
          cmake ..
          cmake --build . --config Release
          sudo cmake --install .
        shell: bash

      - name: CMake Build
        run: |
          export pybind11_DIR=/usr/local/share/cmake/pybind11/
          cd ${{ github.workspace }}
          mkdir build
          cd build
          cmake .. -DENABLE_TESTS=on -DENABLE_PYLIB=on -DCMAKE_BUILD_TYPE:STRING=Release
          cmake --build .
        shell: bash 

      - name: Ctest
        run: |
          cd ${{ github.workspace }}/build
          ctest --output-on-failure -C Release -VV
        shell: bash
      - name: Valgrind
        run: |
          sudo apt-get install valgrind -y
          cd ${{ github.workspace }}/build
          valgrind --leak-check=full --show-leak-kinds=all --errors-for-leak-kinds=all --error-exitcode=1 ./bin/OpenOasis 
        shell: bash
        
